### ISSUE TITLE
The minified build is broken

### ISSUE THREAD

**Issue by evanw** [Agoric/realms-shim#60]
Repro:

1. Check out v1.1.2.
2. Follow the instructions to build the shim.
3. Create a html file containing this:

```html
<body></body>
<script src="dist/realms-shim.umd.min.js"></script>
<script>Realm.makeRootRealm()</script>
```

4. Open it.

Unexpected: `Realm.makeRootRealm()` crashes with `ReferenceError: Z is not defined`.

This is because the minifier is minifying the name `globalEval` in `repairFunctions`, which is then converted to a string and joined with a string that defines `globalEval`.

This is also a problem with v1.1.1 but not with v1.1.0.

**Comment by warner** [comment]
Should we enable CI for the new `shim:test-integration` command? Running `npm run build && npm run shim:test-integration` locally fails:

```
ok 8 new Real() should throws
# Realm.makeRootRealm()
ReferenceError: _315‍ is not defined
    at a (eval at createNewUnsafeRec (/home/warner/bindmounts/trees/realms-shim/dist/realms-shim.esm.min.js:1:5968), <anonymous>:1)
    at repairFunctions (eval at createNewUnsafeRec (/home/warner/bindmounts/trees/realms-shim/dist/realms-shim.esm.min.js:1:5968), <anonymous>:1)
    at eval (eval at createNewUnsafeRec (/home/warner/bindmounts/trees/realms-shim/dist/realms-shim.esm.min.js:1:5968), <anonymous>:1)
    at eval (<anonymous>)
    at createNewUnsafeRec (/home/warner/bindmounts/trees/realms-shim/dist/realms-shim.esm.min.js:1)
    at initRootRealm (/home/warner/bindmounts/trees/realms-shim/dist/realms-shim.esm.min.js:9:3060)
    at c (/home/warner/bindmounts/trees/realms-shim/dist/realms-shim.esm.min.js:1)
    at TamedFunction.makeRootRealm (/home/warner/bindmounts/trees/realms-shim/dist/realms-shim.esm.min.js:1)
    at Test.<anonymous> (/home/warner/bindmounts/trees/realms-shim/test-integration/realm.esm-min.test.js:13:19)
    at Test.bound [as _cb] (/home/warner/bindmounts/trees/realms-shim/node_modules/tape/lib/test.js:77:32)
```
